### ISSUE TITLE
MOVED response with Cluster mode

### ISSUE THREAD

**Issue by stemis** [predishq/predis#568]
Hello,

I am running version 1.1.1 of Predis
I have a redis cluster with version: 5.0.4 running on AWS ElastiCache

When I try connecting to it using Predis, I keep getting MOVED responses

See my code below
```
$client = new \Predis\Client(
    'tls://clustercfg.mycluster.myaccount.euc1.cache.amazonaws.com',
    ['cluster' => 'redis']
);
$client->set('foo', 'bar');
```

The exception I keep getting is: `MOVED 12182 mycluster-0001-001.mycluster.myaccount.euc1.cache.amazonaws.com:6379`

Is there any way around this so Predis automatically handles this?
I was under the assumption that `['cluster' => 'redis']` would fix it, but it doesn't.

**Comment by nrk** [comment]
Hi @stemis,

The problem in your snippet is that you are passing a string value to the constructor of the client instance which configures it to connect to a single Redis instance even when client options may suggest otherwise. In order to properly configure the client to use aggregate connection backends such as the ones for redis-cluster or redis-sentinel you must always [pass a **list** of strings or named arrays](https://github.com/predishq/predis/tree/v1.1.2#cluster), even when you are specifying the parameters for just one node.
